version: "3" 

services:
  nginx:
    container_name: "${PROJECT_NAME}-nginx"
    build:
      context: "./dockerfiles/nginx"
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - "./src:/var/www/html"
    depends_on:
      - php

  php:
    container_name: "${PROJECT_NAME}-php"
    build:
      context: "./dockerfiles/php"
      dockerfile: Dockerfile
      args:
      - PHP_INI_FILE=./dockerfiles/php/php.ini
    volumes:
      - "./src:/var/www/html"

  mysql:
    container_name: "${PROJECT_NAME}-mysql"
    build:
      context: "./dockerfiles/mysql"
      dockerfile: Dockerfile
    ports:
      - "${DB_PORT}:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DB}"
      - "MYSQL_USER={MYSQL_USER}"
      - "MYSQL_PASSWORD={MYSQL_PASSWORD}"
    volumes:
      - "./data/mysql:/var/lib/mysql"
      
  minio:
    image: 'minio/minio'
    container_name: minio
    environment:
        MINIO_ROOT_USER: "${MINIO_USER}"
        MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
    entrypoint: bash
    command: -c "/opt/bin/minio server /export --address :9999 --console-address :9000"
    volumes:
        - ./data/minio:/export
    ports:
        - '9999:9999'
        - '9000:9000'