version: "3" 

services:
  nginx:
    container_name: "${PROJECT_NAME}-nginx"
    build:
      dockerfile: "./dockerfiles/nginx/Dockerfile"
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - "./src:/var/www/html"
    depends_on:
      - php

  php:
    container_name: "${PROJECT_NAME}-php"
    build:
      dockerfile: "./dockerfiles/php/Dockerfile"
    volumes:
      - "./src:/var/www/html"

  mysql:
    container_name: "${PROJECT_NAME}-mysql"
    build:
      dockerfile: "./dockerfiles/mysql/Dockerfile"
    ports:
      - "${DB_PORT}:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DB}"
      - "MYSQL_USER={MYSQL_USER}"
      - "MYSQL_PASSWORD={MYSQL_PASSWORD}"
    volumes:
      - "./data:/var/lib/mysql"