name: Run PHPUnit Tests

on:
  pull_request:
     branches:
      - main
  push:
    branches:
      - develop
      - bugfix

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      APP_ENV: testing
      APP_KEY: base64:uV7+ASG+wtEwhruM8rpMh1Ix9Rf6gZU6TlUzTnT4oOM=
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: my-laravel-app:latest
          
      
      - name: Install Dependencies
        run: |
          docker-compose run --rm app composer install --no-progress --no-interaction --prefer-dist
          
      - name: Run Tests
        run: |
          docker-compose run --rm app php artisan config:cache
          docker-compose run --rm app php artisan migrate --force
          docker-compose run --rm app vendor/bin/phpunit