name: PhpUnitCoverage

on:
  pull_request:
     branches:
      - main
  push:
    branches:
      - develop
      - bugfix

jobs:
  build:
    # 実行環境
    runs-on: ubuntu-latest
    steps:
      # $GITHUB_WORKSPACE配下のリポジトリをチェックアウトしてアクセス可能にする
      - uses: actions/checkout@v2

      - name: dokcer-compose php Init
        run: |
          docker-compose up -d
          docker-compose exec -T php bash -c "composer install"
          docker-compose exec -T php bash -c "cp .env.example .env"
          docker-compose exec -T php bash -c "php artisan key:generate"
          docker-compose exec -T php bash -c "php artisan config:cache"
          docker-compose exec -T php bash -c "sleep 200"

      - name: Exec Phpunit
        run: |
          docker-compose exec -T php bash -c "phpdbg -qrr ./vendor/bin/phpunit --coverage-text --colors=never > storage/logs/coverage.log"
          docker-compose exec -T php bash -c "cat storage/logs/coverage.log"

      - name: Cat Test Result
        run: |
          cat ./src/storage/logs/coverage.log
        if: ${{ failure() }}

      - name: Sed Coverage Report
        run: |
          sed -E "s/"$'\E'"\[([0-9]{1,2}(;[0-9]{1,2})*)?m//g" | \
          grep "Code Coverage Report:" -A6 ./src/storage/logs/coverage.log | sed -e "s/^ *//" | sed -e "s/ *$//" | sed -e "/^ *$/d" > ./src/storage/logs/coverage-summary.log

      - name: Read coverage summary
        id: coverage-summary
        uses: juliangruber/read-file-action@v1
        with:
          path: ./src/storage/logs/coverage-summary.log

      - name: Comment Coverage Summary
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: coverage-summary
          message: |
            ## Coverage Summary
            ${{ steps.coverage-summary.outputs.content }}