name: Run PHPUnit Tests

on:
  pull_request:
     branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build and start containers
        run: |
          docker-compose build
          docker-compose up -d
          
      - name: Install Dependencies
        run: |
          docker-compose run --rm php composer install --no-progress --no-interaction --prefer-dist
          
      - name: Run Tests
        run: |
          docker-compose run --rm php php artisan config:cache
          docker-compose run --rm php php artisan migrate --force
          docker-compose run --rm php vendor/bin/phpunit
          
      - name: Stop containers
        run: docker-compose down